#docker compose file
version: '3.1'

networks:
  project:

services:
  redis:
    image: redis:alpine
    ports:
     - 6379:6379
    #volumes:
    #  - redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - project

